
from os import strerror

for i in range(43):
    print(strerror(i))